In [2]:
import plotly.figure_factory as ff
import pandas as pd 

df = pd.read_csv('./covid19-in-usa/us_states_covid19_daily.csv')

In [4]:
df.head()

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200404,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,...,16.0,6040,6040,6040,2,2.0,1.0,10.0,14.0,24.0
1,20200404,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,...,16.0,6040,6040,6040,2,0.0,0.0,0.0,0.0,0.0
2,20200404,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,...,16.0,6040,6040,6040,2,0.0,0.0,0.0,0.0,0.0
3,20200404,AK,171.0,5869.0,NaN,NaN,16.0,NaN,NaN,NaN,...,16.0,6040,6040,6040,2,0.0,0.0,0.0,0.0,0.0
4,20200404,AL,1580.0,9273.0,NaN,NaN,212.0,NaN,NaN,NaN,...,212.0,10853,10853,10853,1,8.0,212.0,1086.0,148.0,1234.0

AttributeError: 'DataFrame' object has no attribute 'sort'